### ISSUE TITLE
Add the ability to get the count of objects in your storage

### ISSUE THREAD

**Issue by Eyremba** [DeBukkIt/SimpleFileStorage#3]
Here is what I have added to my FileStorage file:

`public int getCountAsInt(){
    return storageMap.size();
  }`

And:

`public String getCountAsString(){
    return String.valueOf(storageMap.size());
  }`

**Comment by DeBukkIt** [comment]
I like your suggestion. However, I would restrict it to getCount returning an int value. The corresponding string representation should be implemented by each user. I'll implement it soon.

**Comment by Eyremba** [comment]
Nice. :)

Thanks.

**Comment by DeBukkIt** [comment]
There it is (again): 5a204966b85f4d8cf100e205e72e053157620b44 called _getSize()_
