### ISSUE TITLE
Add the ability to store data in an encrypted format

### ISSUE THREAD

**Issue by Eyremba** [DeBukkIt/SimpleFileStorage#4]
Improvement suggestion: Add the ability to store data in an encrypted format, for example with AES encryption and with a key that can be specified when an object is stored in the database.

**Comment by DeBukkIt** [comment]
Good idea! I have already prepared a small tool for encryption and decryption of objects (and, for example, built into my SimpleServerClient project). I will implement it very soon in the FileStorage class, too.

**Comment by Eyremba** [comment]
Very nice. :)

Maybe I make also some pull requests in the next days when I found some things to improve. :)

**Comment by Eyremba** [comment]
> I will implement it very soon in the FileStorage class, too.

And when? :P

**Comment by DeBukkIt** [comment]
I've added two methods accepting a password for optional encryption and decryption. Along with the new classes from the Crypt package, it should work.
