### ISSUE TITLE
Unendlichschleife in Crypter.java

### ISSUE THREAD

**Issue by lucasl0st** [DeBukkIt/SimpleFileStorage#9]
In der Datei Crypter.java zeile 121 wird in der while schleife anstatt resultKey key verwendet.
Dadurch ensteht eine unendlichschleife die am ende in einem Java Heap Space error endet.

**Comment by DeBukkIt** [comment]
Vollkommen richtig. Das Problem sollte mit 8862ce45a7519281bc66ed497a5b2cdc689a5639 gelöst worden sein. Vielen Dank für deine Mithilfe!
